Repository AY2324S2-CS2103T-W08-2/tp, pull requests merged in 2024-03, with the labels that each got.

#30 Update AboutUs page
  docs/AboutUs.md
  docs/images/ella-e.png
  docs/team/ella-e.md
Labels: priority.High, v1.1

#36 Update Glossary
  docs/DeveloperGuide.md
Labels: priority.High, v1.1

#32 Update target user profile and value proposition
  docs/DeveloperGuide.md
Labels: priority.High, v1.1

#37 Update Readme and AboutUs
  README.md
  docs/AboutUs.md
  docs/images/mayuehan.png
Labels: priority.High, v1.1

#54 Javierng2knus identificationinformation commands
  src/main/java/vitalconnect/logic/Messages.java
  src/main/java/vitalconnect/logic/commands/AddCommand.java
  src/main/java/vitalconnect/logic/commands/EditCommand.java
  src/main/java/vitalconnect/logic/parser/AddCommandParser.java
  src/main/java/vitalconnect/logic/parser/CliSyntax.java
  src/main/java/vitalconnect/logic/parser/EditCommandParser.java
  src/main/java/vitalconnect/logic/parser/ParserUtil.java
  src/main/java/vitalconnect/model/ModelManager.java
  src/main/java/vitalconnect/model/person/Person.java
  src/main/java/vitalconnect/model/person/identificationinformation/IdentificationInformation.java
  src/main/java/vitalconnect/model/person/identificationinformation/NameContainsKeywordsPredicate.java
  src/main/java/vitalconnect/model/person/identificationinformation/Nric.java
  src/main/java/vitalconnect/model/util/SampleDataUtil.java
  src/main/java/vitalconnect/storage/JsonAdaptedPerson.java
  src/main/java/vitalconnect/ui/PersonCard.java
  src/main/java/vitalconnect/ui/PersonListPanel.java
  src/main/resources/view/PersonListCard.fxml
  src/test/data/JsonClinicStorageTest/invalidAndValidPersonClinic.json
  src/test/data/JsonClinicStorageTest/invalidPersonClinic.json
  src/test/data/JsonSerializableClinicTest/duplicatePersonClinic.json
  src/test/data/JsonSerializableClinicTest/invalidPersonClinic.json
  src/test/data/JsonSerializableClinicTest/typicalPersonsClinic.json
  src/test/java/vitalconnect/logic/LogicManagerTest.java
  src/test/java/vitalconnect/logic/commands/CommandTestUtil.java
  src/test/java/vitalconnect/logic/commands/EditCommandTest.java
  src/test/java/vitalconnect/logic/commands/EditPersonDescriptorTest.java
  src/test/java/vitalconnect/logic/parser/AddCommandParserTest.java
  src/test/java/vitalconnect/logic/parser/CreateAptCommandParserTest.java
  src/test/java/vitalconnect/logic/parser/EditCommandParserTest.java
  src/test/java/vitalconnect/model/ClinicTest.java
  src/test/java/vitalconnect/model/ModelManagerTest.java
  src/test/java/vitalconnect/model/person/PersonTest.java
  src/test/java/vitalconnect/model/person/UniquePersonListTest.java
  src/test/java/vitalconnect/model/person/identificationinformation/NameContainsKeywordsPredicateTest.java
  src/test/java/vitalconnect/storage/JsonAdaptedPersonTest.java
  src/test/java/vitalconnect/testutil/EditPersonDescriptorBuilder.java
  src/test/java/vitalconnect/testutil/PersonBuilder.java
  src/test/java/vitalconnect/testutil/PersonUtil.java
  src/test/java/vitalconnect/testutil/TypicalPersons.java
Labels: priority.High, v1.2

#60 Update help command to reflect user guide
  src/main/java/vitalconnect/ui/HelpWindow.java
Labels: priority.High, v1.2

#59 Fulfil test coverage
  src/main/java/vitalconnect/model/person/identificationinformation/IdentificationInformation.java
  src/test/java/vitalconnect/model/person/identificationinformation/IdentificationInformationTest.java
  src/test/java/vitalconnect/model/person/identificationinformation/NricTest.java
Labels: type.Chore, severity.High, v1.2

#62 Fix Junit test issue
  src/test/java/vitalconnect/logic/commands/CreateAptCommandTest.java
Labels: type.Bug, priority.Medium

#75 Improve UI
  src/main/java/vitalconnect/ui/PersonCard.java
Labels: priority.Medium, severity.Medium, v1.2b

#61 Implement the Storage and GUI for Appointment
  build.gradle
  src/main/java/vitalconnect/MainApp.java
  src/main/java/vitalconnect/logic/Logic.java
  src/main/java/vitalconnect/logic/LogicManager.java
  src/main/java/vitalconnect/logic/commands/CommandResult.java
  src/main/java/vitalconnect/logic/commands/CreateAptCommand.java
  src/main/java/vitalconnect/logic/commands/DeleteAptCommand.java
  src/main/java/vitalconnect/logic/commands/ExitCommand.java
  src/main/java/vitalconnect/logic/commands/HelpCommand.java
  src/main/java/vitalconnect/logic/commands/ListAptCommand.java
  src/main/java/vitalconnect/logic/parser/CreateAptCommandParser.java
  src/main/java/vitalconnect/model/Appointment.java
  src/main/java/vitalconnect/model/Model.java
  src/main/java/vitalconnect/model/ModelManager.java
  src/main/java/vitalconnect/model/ReadOnlyUserPrefs.java
  src/main/java/vitalconnect/model/UserPrefs.java
  src/main/java/vitalconnect/storage/AppointmentStorage.java
  src/main/java/vitalconnect/storage/JsonAdaptedAppointment.java
  src/main/java/vitalconnect/storage/JsonAppointmentStorage.java
  src/main/java/vitalconnect/storage/JsonSerializableAppointment.java
  src/main/java/vitalconnect/storage/Storage.java
  src/main/java/vitalconnect/storage/StorageManager.java
  src/main/java/vitalconnect/ui/AppointmentCard.java
  src/main/java/vitalconnect/ui/AppointmentListPanel.java
  src/main/java/vitalconnect/ui/MainWindow.java
  src/main/resources/view/AppointmentListCard.fxml
  src/main/resources/view/AppointmentListPanel.fxml
  src/test/data/JsonSerializableAppointmentTest/invalidAppointment.json
  src/test/data/JsonSerializableAppointmentTest/typicalAppointments.json
  src/test/java/vitalconnect/logic/LogicManagerTest.java
  src/test/java/vitalconnect/logic/commands/AddCommandIntegrationTest.java
  src/test/java/vitalconnect/logic/commands/AddCommandTest.java
  src/test/java/vitalconnect/logic/commands/AddContactCommandTest.java
  src/test/java/vitalconnect/logic/commands/ClearCommandTest.java
  src/test/java/vitalconnect/logic/commands/CommandResultTest.java
  src/test/java/vitalconnect/logic/commands/CreateAptCommandTest.java
  src/test/java/vitalconnect/logic/commands/DeleteAptCommandTest.java
  src/test/java/vitalconnect/logic/commands/DeleteCommandTest.java
  src/test/java/vitalconnect/logic/commands/DeleteContactCommandTest.java
  src/test/java/vitalconnect/logic/commands/EditCommandTest.java
  src/test/java/vitalconnect/logic/commands/ExitCommandTest.java
  src/test/java/vitalconnect/logic/commands/FindCommandTest.java
  src/test/java/vitalconnect/logic/commands/HelpCommandTest.java
  src/test/java/vitalconnect/logic/commands/ListAptCommandTest.java
  src/test/java/vitalconnect/logic/commands/ListCommandTest.java
  src/test/java/vitalconnect/logic/commands/ListContactCommandTest.java
  src/test/java/vitalconnect/logic/parser/ClinicParserTest.java
  src/test/java/vitalconnect/logic/parser/CreateAptCommandParserTest.java
  src/test/java/vitalconnect/model/ModelManagerTest.java
  src/test/java/vitalconnect/model/UserPrefsTest.java
  src/test/java/vitalconnect/storage/JsonAppointmentStorageTest.java
  src/test/java/vitalconnect/storage/JsonSerializableAppointmentTest.java
  src/test/java/vitalconnect/storage/StorageManagerTest.java
  src/test/java/vitalconnect/testutil/TypicalAppointment.java
  src/test/java/vitalconnect/ui/UiPartTest.java
Labels: priority.High, v1.2b

#74 Update puml graphs
  docs/DeveloperGuide.md
  docs/diagrams/CommitActivityDiagram.puml
  docs/diagrams/ModelClassDiagram.puml
  docs/diagrams/ParserClasses.puml
  docs/diagrams/StorageClassDiagram.puml
  docs/images/CommitActivityDiagram.png
  docs/images/ModelClassDiagram.png
  docs/images/ParserClasses.png
  docs/images/StorageClassDiagram.png
Labels: type.Chore, priority.High, v1.3

#76 Update UG and list contact information
  docs/UserGuide.md
  docs/images/findJohnResult.png
  src/main/java/vitalconnect/logic/commands/AddMedInfoCommand.java
  src/main/java/vitalconnect/logic/commands/ListContactCommand.java
  src/main/java/vitalconnect/logic/parser/ClinicParser.java
  src/main/java/vitalconnect/model/Model.java
  src/main/java/vitalconnect/model/person/Person.java
Labels: type.Chore, priority.High, v1.3

#79 Update UserGuide
  docs/AboutUs.md
  docs/UserGuide.md
Labels: priority.Medium, v1.3

#81 Update user guide with images
  docs/UserGuide.md
  docs/images/commandsPictures/addCommand.png
  docs/images/commandsPictures/addaCommand.png
  docs/images/commandsPictures/addcCommand.png
  docs/images/commandsPictures/addmCommand.png
  docs/images/commandsPictures/clearCommand.png
  docs/images/commandsPictures/deleteCommand.png
  docs/images/commandsPictures/deleteaCommand.png
  docs/images/commandsPictures/deletecCommand.png
  docs/images/commandsPictures/deletemCommand.png
  docs/images/commandsPictures/findJohnResult.png
  docs/images/commandsPictures/helpMessage.png
  docs/images/commandsPictures/listCommand.png
  docs/images/commandsPictures/listaCommand.png
  docs/images/commandsPictures/listcCommand.png
  docs/images/commandsPictures/listmCommand.png
  docs/images/helpMessage.png
Labels: type.Chore, priority.Medium, v1.3

#83 Add edit contact command; update respective UG; fix CI UI display issue
  docs/UserGuide.md
  docs/images/commandsPictures/editcCommand.png
  src/main/java/vitalconnect/logic/Messages.java
  src/main/java/vitalconnect/logic/commands/EditContactCommand.java
  src/main/java/vitalconnect/logic/commands/ListCommand.java
  src/main/java/vitalconnect/logic/commands/ListContactCommand.java
  src/main/java/vitalconnect/logic/parser/ClinicParser.java
  src/main/java/vitalconnect/logic/parser/EditContactCommandParser.java
  src/main/java/vitalconnect/model/Model.java
  src/main/java/vitalconnect/model/ModelManager.java
  src/main/java/vitalconnect/model/person/contactinformation/ContactInformation.java
  src/test/java/vitalconnect/logic/commands/AddCommandTest.java
  src/test/java/vitalconnect/logic/commands/AddContactCommandTest.java
  src/test/java/vitalconnect/logic/commands/CreateAptCommandTest.java
  src/test/java/vitalconnect/logic/commands/DeleteAptCommandTest.java
  src/test/java/vitalconnect/logic/commands/DeleteContactCommandTest.java
  src/test/java/vitalconnect/logic/commands/ListAptCommandTest.java
Labels: priority.Medium, v1.3

#84 Reformat appointment command
  src/main/java/vitalconnect/logic/commands/CreateAptCommand.java
  src/main/java/vitalconnect/logic/commands/DeleteAptCommand.java
  src/main/java/vitalconnect/logic/parser/CliSyntax.java
  src/main/java/vitalconnect/logic/parser/CreateAptCommandParser.java
  src/main/java/vitalconnect/logic/parser/DeleteAptCommandParser.java
  src/main/java/vitalconnect/logic/parser/ParserUtil.java
  src/test/java/vitalconnect/logic/commands/CreateAptCommandTest.java
  src/test/java/vitalconnect/logic/commands/DeleteAptCommandTest.java
  src/test/java/vitalconnect/logic/parser/ClinicParserTest.java
  src/test/java/vitalconnect/logic/parser/CreateAptCommandParserTest.java
  src/test/java/vitalconnect/logic/parser/DeleteAptCommandParserTest.java
Labels: priority.Medium, v1.3

#86 Add edit medical information function
  docs/UserGuide.md
  src/main/java/vitalconnect/logic/Messages.java
  src/main/java/vitalconnect/logic/commands/EditMedicalCommand.java
  src/main/java/vitalconnect/logic/parser/AddMedicalCommandParser.java
  src/main/java/vitalconnect/logic/parser/CliSyntax.java
  src/main/java/vitalconnect/logic/parser/ClinicParser.java
  src/main/java/vitalconnect/logic/parser/EditMedicalCommandParser.java
  src/main/java/vitalconnect/logic/parser/ParserUtil.java
  src/main/java/vitalconnect/model/person/medicalinformation/AllergyTag.java
  src/main/java/vitalconnect/model/person/medicalinformation/MedicalInformation.java
  src/main/java/vitalconnect/model/util/SampleDataUtil.java
  src/main/java/vitalconnect/storage/JsonAdaptedPerson.java
  src/main/java/vitalconnect/storage/JsonAdaptedTag.java
  src/test/java/vitalconnect/logic/parser/ParserUtilTest.java
  src/test/java/vitalconnect/model/allergytag/AllergyTagTest.java
  src/test/java/vitalconnect/testutil/PersonBuilder.java
Labels: priority.Medium, v1.3

#89 Add time duration for Appointment function
  docs/UserGuide.md
  src/main/java/vitalconnect/logic/commands/CreateAptCommand.java
  src/main/java/vitalconnect/logic/parser/CliSyntax.java
  src/main/java/vitalconnect/logic/parser/CreateAptCommandParser.java
  src/main/java/vitalconnect/logic/parser/ParserUtil.java
  src/main/java/vitalconnect/model/Appointment.java
  src/main/java/vitalconnect/model/Model.java
  src/main/java/vitalconnect/model/ModelManager.java
  src/main/java/vitalconnect/storage/JsonAdaptedAppointment.java
  src/main/java/vitalconnect/ui/AppointmentCard.java
  src/main/resources/view/AppointmentListCard.fxml
  src/test/data/JsonSerializableAppointmentTest/invalidAppointment.json
  src/test/data/JsonSerializableAppointmentTest/typicalAppointments.json
  src/test/java/vitalconnect/logic/commands/AddCommandTest.java
  src/test/java/vitalconnect/logic/commands/AddContactCommandTest.java
  src/test/java/vitalconnect/logic/commands/CreateAptCommandTest.java
  src/test/java/vitalconnect/logic/commands/DeleteAptCommandTest.java
  src/test/java/vitalconnect/logic/commands/DeleteContactCommandTest.java
  src/test/java/vitalconnect/logic/commands/ListAptCommandTest.java
  src/test/java/vitalconnect/logic/parser/ClinicParserTest.java
  src/test/java/vitalconnect/logic/parser/CreateAptCommandParserTest.java
  src/test/java/vitalconnect/model/ModelManagerTest.java
  src/test/java/vitalconnect/storage/JsonSerializableAppointmentTest.java
  src/test/java/vitalconnect/testutil/TypicalAppointment.java
Labels: priority.High, v1.3

#92 Update UI
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/Extensions.css
  src/main/resources/view/MainWindow.fxml
Labels: priority.High

#93 Edit Appointment
  docs/UserGuide.md
  src/main/java/vitalconnect/logic/commands/CreateAptCommand.java
  src/main/java/vitalconnect/logic/commands/EditAppointmentCommand.java
  src/main/java/vitalconnect/logic/parser/CliSyntax.java
  src/main/java/vitalconnect/logic/parser/ClinicParser.java
  src/main/java/vitalconnect/logic/parser/EditAppointmentCommandParser.java
  src/main/java/vitalconnect/model/Appointment.java
  src/main/java/vitalconnect/model/Model.java
  src/main/java/vitalconnect/model/ModelManager.java
  src/main/java/vitalconnect/storage/JsonAdaptedAppointment.java
  src/test/java/vitalconnect/logic/commands/AddCommandTest.java
  src/test/java/vitalconnect/logic/commands/AddContactCommandTest.java
  src/test/java/vitalconnect/logic/commands/CreateAptCommandTest.java
  src/test/java/vitalconnect/logic/commands/DeleteAptCommandTest.java
  src/test/java/vitalconnect/logic/commands/DeleteContactCommandTest.java
  src/test/java/vitalconnect/logic/commands/ListAptCommandTest.java
  src/test/java/vitalconnect/model/ModelManagerTest.java
  src/test/java/vitalconnect/testutil/TypicalAppointment.java
Labels: priority.Medium, v1.3
