Repository AY2324S2-CS2103T-W08-2/tp, pull requests merged in 2024-04, with the labels that each got.

#94 Improve contact
  src/main/java/vitalconnect/logic/Messages.java
  src/main/java/vitalconnect/logic/commands/AddContactCommand.java
  src/main/java/vitalconnect/logic/commands/EditAppointmentCommand.java
  src/main/java/vitalconnect/logic/parser/EditContactCommandParser.java
  src/main/java/vitalconnect/logic/parser/ParserUtil.java
  src/main/java/vitalconnect/model/Appointment.java
  src/main/java/vitalconnect/model/person/contactinformation/Address.java
  src/main/java/vitalconnect/model/person/contactinformation/Email.java
  src/main/java/vitalconnect/model/person/contactinformation/Phone.java
  src/main/java/vitalconnect/model/person/medicalinformation/MedicalInformation.java
  src/main/java/vitalconnect/storage/JsonAdaptedPerson.java
  src/main/java/vitalconnect/ui/PersonCard.java
  src/main/resources/view/PersonListCard.fxml
  src/test/java/vitalconnect/logic/commands/AddContactCommandTest.java
  src/test/java/vitalconnect/logic/commands/CommandTestUtil.java
  src/test/java/vitalconnect/logic/parser/ParserUtilTest.java
  src/test/java/vitalconnect/model/person/contactinformation/AddressTest.java
Labels: priority.Medium, v1.3

#99 UI center split
  src/main/java/vitalconnect/model/person/contactinformation/ContactInformation.java
  src/main/java/vitalconnect/model/person/medicalinformation/MedicalInformation.java
  src/main/java/vitalconnect/ui/PersonCard.java
  src/main/resources/view/DarkTheme.css
  src/main/resources/view/PersonListCard.fxml
Labels: priority.Medium, v1.3

#101 New finda command and delete patient's appointment when delete person
  src/main/java/vitalconnect/logic/Logic.java
  src/main/java/vitalconnect/logic/LogicManager.java
  src/main/java/vitalconnect/logic/Messages.java
  src/main/java/vitalconnect/logic/commands/CommandResult.java
  src/main/java/vitalconnect/logic/commands/DeleteCommand.java
  src/main/java/vitalconnect/logic/commands/FindAptCommand.java
  src/main/java/vitalconnect/logic/parser/ClinicParser.java
  src/main/java/vitalconnect/logic/parser/CreateAptCommandParser.java
  src/main/java/vitalconnect/logic/parser/FindAptCommandParser.java
  src/main/java/vitalconnect/model/Clinic.java
  src/main/java/vitalconnect/model/Model.java
  src/main/java/vitalconnect/model/ModelManager.java
  src/main/java/vitalconnect/ui/MainWindow.java
  src/main/resources/view/DarkTheme.css
  src/test/java/vitalconnect/logic/commands/AddCommandTest.java
  src/test/java/vitalconnect/logic/commands/AddContactCommandTest.java
  src/test/java/vitalconnect/logic/commands/CreateAptCommandTest.java
  src/test/java/vitalconnect/logic/commands/DeleteAptCommandTest.java
  src/test/java/vitalconnect/logic/commands/DeleteContactCommandTest.java
  src/test/java/vitalconnect/logic/commands/ListAptCommandTest.java
Labels: priority.High

#104 User guide
  docs/UserGuide.md
Labels: v1.3

#105 Update User Guide for Appointment commands
  docs/UserGuide.md
  src/main/java/vitalconnect/logic/commands/FindAptCommand.java
Labels: priority.High

#108 Branch timetable
  build.gradle
  src/main/java/vitalconnect/ui/MainWindow.java
  src/main/java/vitalconnect/ui/Timetable.java
  src/main/resources/view/MainWindow.fxml
  src/main/resources/view/Timetable.fxml
Labels: priority.Medium, v1.3

#168 Branch fix #159
  src/main/java/vitalconnect/ui/Timetable.java
Labels: type.Bug

#170 Branch fix #164#142
  docs/UserGuide.md
  src/main/java/vitalconnect/ui/MainWindow.java
  src/main/resources/view/MainWindow.fxml
Labels: type.Bug, severity.Low

#173 Branch junit test
  src/main/java/vitalconnect/model/person/medicalinformation/Height.java
  src/main/java/vitalconnect/model/person/medicalinformation/Weight.java
  src/test/java/vitalconnect/model/person/meidcalinformation/AllergyTagTest.java
  src/test/java/vitalconnect/model/person/meidcalinformation/HeightTest.java
  src/test/java/vitalconnect/model/person/meidcalinformation/MedicalInformationTest.java
  src/test/java/vitalconnect/model/person/meidcalinformation/WeightTest.java
Labels: v1.4

#199 Branch sync timetable
  src/main/java/vitalconnect/model/ModelManager.java
  src/main/java/vitalconnect/ui/MainWindow.java
  src/main/java/vitalconnect/ui/Timetable.java
Labels: type.Bug, v1.4

#198 Update the DG and UI
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/resources/view/AppointmentListCard.fxml
  src/main/resources/view/PersonListCard.fxml
Labels: v1.4

#204 Fix
  src/main/java/vitalconnect/ui/Timetable.java
Labels: type.Bug, priority.High, v1.4

#205 Edit the diagram in DG
  docs/DeveloperGuide.md
  docs/diagrams/StorageClassDiagram.puml
  docs/diagrams/UiClassDiagram.puml
Labels: v1.4

#208 Update DG
  docs/DeveloperGuide.md
  docs/diagrams/UiClassDiagram.puml
  docs/images/UiClassDiagram.png
Labels: priority.High, v1.4
